### ISSUE TITLE
Implement file lock feature for Dropbox

### ISSUE THREAD

**Issue by FeBe95** [eight04/db-to-cloud#13]
Good day sir,

I have a suggestion for improving the sync workflow with Dropbox:

Every time a sync is being done the client receives a Desktop notification, saying "lock.json was added" and "lock.json was deleted". This message could be suppressed by the `mute` parameter that exists for the `/upload` endpoint (see https://www.dropbox.com/developers/documentation/http/documentation#files-upload).

Another idea could be locking the relevant files with the natively supported `files-lock_file_batch` endpoint (see https://www.dropbox.com/developers/documentation/http/documentation#files-lock_file_batch).

Thank You!

**Comment by eight04** [comment]
> `mute` parameter

Maybe we should use it on all files not just `lock.json`?

>  `files-lock_file_batch`

The document is a little unclear. What is a "lock holder"? And it doesn't seem to support an expiry date.

**Comment by FeBe95** [comment]
> Maybe we should use it on all files not just `lock.json`?

Even better.

> The document is a little unclear.

That's right. Maybe this is not a use case where to use this endpoint. Seems like it is rather for shared files since the error `file_not_shared` exists for it.
